changes on checking the conditions fot dtmc matrix
copa-uniandes/jmarkov pull request #1
Opened 2024-01-29 02:27 UTC by mgabyurango

taking into account if the values of the matrix are positive and if the sum of the rows equals 1

2024-01-31 14:46 UTC, juanfperez commented on jmarkov/dtmc.py
> +from markov_chain import markov_chain
por qué cambiaste el import a sin el punto?

2024-01-31 14:54 UTC, juanfperez requested changes
revisa por favor la comparación con .isclose de numpy y agrega un par de casos de prueba

2024-01-31 14:54 UTC, juanfperez commented on jmarkov/dtmc.py
> +        if 0.99<=sum(M.T).all()<=1:
aquí creo que es mejor usar .isclose() de numpy para comparar los vectores

2024-02-01 01:28 UTC, mgabyurango commented on jmarkov/dtmc.py
> +from markov_chain import markov_chain
no me corría :/ 
me salía un error extraño pero cuando lo quité me empezó a funcionar

2024-02-05 00:00 UTC, mgabyurango commented on jmarkov/dtmc.py
> +        if 0.99<=sum(M.T).all()<=1:
Listo el cambio! Revisalo y estoy pendiente

2024-02-07 19:14 UTC, juanfperez approved these changes

2024-02-07 19:16 UTC, mgabyurango commented
[celebrate]     Maria Gabriela Urango Llorente reacted to your message:
________________________________
From: juanfperez ***@***.***>
Sent: Wednesday, February 7, 2024 7:14:10 PM
To: copa-uniandes/jmarkov ***@***.***>
Cc: Maria Gabriela Urango Llorente ***@***.***>; Author ***@***.***>
Subject: Re: [copa-uniandes/jmarkov] changes on checking the conditions fot dtmc matrix (PR #1)


@juanfperez approved this pull request.

—
Reply to this email directly, view it on GitHub<https://github.com/copa-uniandes/jmarkov/pull/1#pullrequestreview-1868584502>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BCCSCKLWBRWCV7B46C2YNRTYSPHAFAVCNFSM6AAAAABCOVPXG2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQNRYGU4DINJQGI>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-02-08 13:27 UTC, merged